---
- hosts: localhost
  connection: local
  tasks:
   - name: Create log file
     copy:
      dest:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      content: "id,run_stage,power"

- hosts: localhost
  tasks:
   - name: run node script
     command: node ../power_off.js

   - name: let switch init
     pause:
       seconds: 30

   - name: run node script
     command: node ../power_on.js

   - name: let switch init
     pause:
       seconds: 300

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      line: "{{ run_id }},reboot,{{ out.stdout_lines[1] }}"
      insertbefore: EOF

- hosts: data_plane
  become: yes
  tasks:
   - import_tasks: start_empty_mat_tests.playbook.yml
     environment:
       SDE_INSTALL: /home/ubuntu/bf-sde-9.7.0/install
       SDE: /home/ubuntu/bf-sde-9.7.0
       BSP_INSTALL: /home/ubuntu/bf-sde-9.7.0/install
       P4SRC: /home/ubuntu/p4-mat-tests

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      line: "{{ run_id }},idle,{{ out.stdout_lines[1] }}"
      insertbefore: EOF

- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 20

   - name: Callibration start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py -d 120 -o results/ --mult 100% -l sessions.json
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

# TRAFFIC 100% {
   - name: Real start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py -d 240 -o results/ --mult 100% -l sessions.json
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      line: "{{ run_id }},traffic_100,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 100%
#
# TRAFFIC 80% {
- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 20

   - name: Real start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py -d 240 -o results/ --mult 80% -l sessions.json
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      line: "{{ run_id }},traffic_80,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 80%

# TRAFFIC 60% {
- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 120

- hosts: traffic_gen
  become: yes
  tasks:
   - name: start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py  -d 240 -o results/ --mult 60% -l sessions.json
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      line: "{{ run_id }},traffic_60,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 60%

# TRAFFIC 40% {
- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 120

- hosts: traffic_gen
  become: yes
  tasks:
   - name: start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py  -d 240 -o results/ --mult 40% -l sessions.json
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      line: "{{ run_id }},traffic_40,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 40%
#
# TRAFFIC 20% {
- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 120

- hosts: traffic_gen
  become: yes
  tasks:
   - name: start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py  -d 240 -o results/ --mult 20% -l sessions.json
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      line: "{{ run_id }},traffic_20,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 20%
#
# TRAFFIC 5% {
- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 120

- hosts: traffic_gen
  become: yes
  tasks:
   - name: start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py  -d 240 -o results/ --mult 5% -l sessions.json
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "S9180-EMPTY-{{ date }}-{{ run_id }}.csv"
      line: "{{ run_id }},traffic_20,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 5%
