---
- hosts: all
  connection: local
  tasks:
  - name: set fact
    set_fact: file_name = "MAT-SRAM-{{ date }}"

- hosts: localhost
  connection: local
  tasks:
   - name: Create log file
     copy:
      dest:  "MAT-SRAM-{{ date }}-{{ run_id }}"
      content: "id,run_stage,power"

- hosts: localhost
  tasks:
   - name: run node script
     command: node ../power_off.js

   - name: let switch init
     pause:
       seconds: 30

   - name: run node script
     command: node ../power_on.js

   - name: let switch init
     pause:
       seconds: 300

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "MAT-SRAM-{{ date }}"
      line: "{{ run_id }},reboot,{{ out.stdout_lines[1] }}"
      insertbefore: EOF

- hosts: data_plane
  become: yes
  tasks:
   - import_tasks: start_mat_mat_tests.playbook.yml
     environment:
       SDE_INSTALL: /home/ubuntu/bf-sde-9.9.0/install
       SDE: /home/ubuntu/bf-sde-9.9.0
       BSP_INSTALL: /home/ubuntu/bf-sde-9.9.0/install
       P4SRC: /home/ubuntu/p4-mat-tests

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "MAT-SRAM-{{ date }}"
      line: "{{ run_id }},idle,{{ out.stdout_lines[1] }}"
      insertbefore: EOF

- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 20

   - name: Callibration start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py -d 120 -o results/ --mult 100% 
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

# TRAFFIC 100% {
   - name: Real start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py -d 240 -o results/ --mult 100% 
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "MAT-SRAM-{{ date }}"
      line: "{{ run_id }},traffic_100,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 100%

# TRAFFIC 50% {
- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "MAT-SRAM-{{ date }}"
      line: "{{ run_id }},between,{{ out.stdout_lines[1] }}"
      insertbefore: EOF

- hosts: traffic_gen
  become: yes
  tasks:
   - name: start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py  -d 240 -o results/ --mult 50%
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "MAT-SRAM-{{ date }}"
      line: "{{ run_id }},traffic_50,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 50%

# TRAFFIC 10% {
- hosts: traffic_gen
  become: yes
  tasks:
   - name: restart trex-server
     service:
       name: trex-server
       state: restarted
     async: 100000
     poll: 0

   - name: let trex start
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "MAT-SRAM-{{ date }}"
      line: "{{ run_id }},between2,{{ out.stdout_lines[1] }}"
      insertbefore: EOF

- hosts: traffic_gen
  become: yes
  tasks:
   - name: start traffic
     command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_normal_traffic.py  -d 240 -o results/ --mult 10%
     async: 10000
     poll: 0
     become: yes
     args:
       chdir: /opt/trex/v2.97/

   - name: let switch init
     pause:
       seconds: 120

- hosts: localhost
  connection: local
  tasks:
   - name: run node script
     command: node ../get_power_read.js
     register: out

   - lineinfile:
      path:  "MAT-SRAM-{{ date }}"
      line: "{{ run_id }},traffic_10,{{ out.stdout_lines[1] }}"
      insertbefore: EOF
# } TRAFFIC 10%
