---
- hosts: data_plane
  become: yes
  tasks:
    - import_tasks: start_mat_tests.playbook.yml
      environment:
        SDE_INSTALL: /home/ubuntu/bf-sde-9.9.0/install
        SDE: /home/ubuntu/bf-sde-9.9.0
        BSP_INSTALL: /home/ubuntu/bf-sde-9.9.0/install
        P4SRC: /home/ubuntu/p4-mat-tests/

- hosts: traffic_gen
  become: yes
  tasks:
    - name: restart trex-server
      service:
        name: trex-server
        state: restarted
      async: 100000
      poll: 0

    - name: let trex start
      pause:
        seconds: 20

    - name: start traffic
      command: python3 automation/trex_control_plane/interactive/trex/examples/stl/stl_gtp.py -l ./sessions.json -n {{ n_clients }} --latency True -d 60 -o results/
      become: yes
      args:
        chdir: /opt/trex/v2.97/

    - name: copy logs
      fetch:
        src: /opt/trex/v2.97/results/results.json
        dest: ./sram-results-{{ run_id }}-{{ n_clients }}

    - name: delete results
      file:
        state: absent
        path: /opt/trex/v2.97/results/
