---
#- name: Start kernel driver
#  command: "$SDE_INSTALL/bin/bf_kdrv_mod_load $SDE_INSTALL"

- name: "copy files to $SDE_INSTALL"
  command: cp -r $P4SRC/mat-tests.tofino $SDE_INSTALL
  args:
    chdir: $P4SRC

- name: "start UP"
  command: $SDE/run_switchd.sh -p switch -c mat-tests.tofino/mat-tests.conf
  async: 1000000
  poll: 0
  register: out
  args:
    chdir: $P4SRC

- name: let switch init
  pause:
    seconds: 15

- name: "load dp instructions"
  command: python3 mat-tests-cp.py
  args:
    chdir: $P4SRC
