---
- name: github/modules
  command: "bash i2c_utils_std.sh i2c_test_all"
  ignore_errors: True
  args:
    chdir: /home/ubuntu/github/platform_init

- name: Start kernel driver
  command: "$SDE_INSTALL/bin/bf_kdrv_mod_load $SDE_INSTALL"
  ignore_errors: True

- name: "copy files to $SDE_INSTALL"
  command: cp -r tests/mat-tests-empty.tofino $SDE_INSTALL
  args:
    chdir: $P4SRC

- name: "start UP"
  command: $SDE/run_switchd.sh -p switch -c mat-tests-empty.tofino/mat-tests-empty.conf
  async: 1000000
  poll: 0
  register: out
  args:
    chdir: $P4SRC

- name: let switch init
  pause:
    seconds: 15

- name: "load dp instructions"
  command: python3 mat-tests-cp.py
  args:
    chdir: $P4SRC
  ignore_errors: True
 
  # - name: "copy experiment logs"
  #   fetch:
  #     src: $P4SRC/mat-tests-empty.tofino/pipe/logs/{{ item }}
  #     dest: ./empty-results-{{ run_id }}
  #   environment:
  #     SDE_INSTALL: /home/ubuntu/bf-sde-9.9.0/install
  #     SDE: /home/ubuntu/bf-sde-9.9.0
  #     BSP_INSTALL: /home/ubuntu/bf-sde-9.9.0/install
  #     P4SRC: /home/ubuntu/p4-mat-tests/
  #   with_items:
  #     - mau.json
  #     - mau.power.log
  #     - power.json
  #     - resources.json
  #     - table_summary.log
  #     - mau.resources.log
  #     - mau.characterize.log
